// <auto-generated />
using System;
using BlazorServer.FactoryPatternExample.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorServer.FactoryPatternExample.Migrations
{
    [DbContext(typeof(FactoryPatternExampleContext))]
    partial class FactoryPatternExampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("BlazorServer.FactoryPatternExample.Domain.models.Order", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmountOrder")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ShippingCost")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.Property<int?>("StateId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Total")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StateId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOrder = 1,
                            Comment = "Order 1",
                            Description = "Order 1",
                            Name = "Order 1",
                            ProductId = 1,
                            ShippingCost = 10.0,
                            StateId = 1,
                            Total = 1009.99
                        },
                        new
                        {
                            Id = 2,
                            AmountOrder = 1,
                            Comment = "Order 2",
                            Description = "Order 2",
                            Name = "Order 2",
                            ProductId = 1,
                            ShippingCost = 20.0,
                            StateId = 2,
                            Total = 1019.99
                        },
                        new
                        {
                            Id = 3,
                            AmountOrder = 1,
                            Comment = "Order 3",
                            Description = "Order 3",
                            Name = "Order 3",
                            ProductId = 1,
                            ShippingCost = 50.0,
                            StateId = 3,
                            Total = 1059.99
                        });
                });

            modelBuilder.Entity("BlazorServer.FactoryPatternExample.Domain.models.Product", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Cost")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "This is a Car",
                            Cost = 999.99000000000001,
                            Description = "Car",
                            Name = "Civic"
                        },
                        new
                        {
                            Id = 2,
                            Comment = "This is a Bus",
                            Cost = 9999.9899999999998,
                            Description = "Bus",
                            Name = "Grey Hound"
                        },
                        new
                        {
                            Id = 3,
                            Comment = "This is a Truck",
                            Cost = 4999.9899999999998,
                            Description = "Truck",
                            Name = "Tacoma"
                        });
                });

            modelBuilder.Entity("BlazorServer.FactoryPatternExample.Domain.models.State", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CA",
                            Comment = "California",
                            Description = "California",
                            Name = "California"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "AZ",
                            Comment = "Arizona",
                            Description = "Arizona",
                            Name = "Arizona"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "NY",
                            Comment = "New York",
                            Description = "New York",
                            Name = "New York"
                        });
                });

            modelBuilder.Entity("BlazorServer.FactoryPatternExample.Domain.models.Order", b =>
                {
                    b.HasOne("BlazorServer.FactoryPatternExample.Domain.models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorServer.FactoryPatternExample.Domain.models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("State");
                });
#pragma warning restore 612, 618
        }
    }
}
